// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package database

import (
	"context"
)

const resetChirps = `-- name: ResetChirps :exec
DELETE FROM chirps
`

func (q *Queries) ResetChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetChirps)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
